name = input ("Hello. What is your name? ")
name = name.title().strip()
print ("Hello there " + name)
drink = input ("What do you Like to drink? ")
drink = drink.title().strip()
print ("I also enjoy to drink " + drink)
hobby = input ("What is your favorite hobby " + name)
hobby = hobby.title().strip()
print ("Well...I Have never heard of " + hobby)
travel = input ("If I have never heard of that I should get out more often, where should I go " + name)
tavel = travel.title().strip()
pack = input ("Ok Thanks! I will start packing now.....Wait I am a computer, What do I pack? ")
pack = pack.title().strip()
print ("How could I forget the " + pack)
print = input ("Thank you for helping me, I will see you in " + travel)
print = input ("Goodbye " + name) 
