name = input ("Hello. What is your name?")
print ("Hello there" + name)
drink = input ("What do you Like to drink?")
print ("I also enjoy to drink" + drink)
hobby = input ("What is your favorite hobby" + name)
print ("Well...I Have never heard of" + hobby)
travel = input ("If I have never heard of that I should get out more often, where should I go" + name)
pack = input ("Ok Thanks! I will start packing now.....Wait I am a computer, What do I pack?")
print ("How could I forget the" + pack)
print = input ("Thank you for helping me, I will see you in" + travel)
print = input ("Goodbye" + name) 
